title: Leonardo G. Hern√°ndez
description: Industrial Engineer | Optimization, Analytics and AI
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: air

navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /assets/pdf/CV_Leonardo_Hernandez.pdf
  - title: "Contact"
    url: /contact/
