title: Leonardo G. Hern√°ndez
description: Industrial Engineer | Optimization, Analytics and AI
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "air"  # limpio y profesional
