title: Leonardo G. Hern√°ndez
description: Industrial Engineer | Optimization, Analytics and AI
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "air"  # limpio y profesional

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /assets/pdf/CV_Leonardo_Hernandez.pdf
  - title: "Contact"
    url: /contact/
