title: Leonardo G. Hernández
description: Industrial Engineer | Optimization, Analytics and AI
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: air

locale: "en-US"
url: "https://leogasis.github.io" # Verify this is the correct base URL

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/
    
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  # _projects
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "single"
      author_profile: true
      share: true


author:
  name: "Leonardo G. Hernández Landa, PhD"
  bio: "Industrial Engineer | Optimization | Artificial Intelligence"
  avatar: "/assets/images/profile.png"
  location: "Monterrey, Mexico"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:leogabrielhdz@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leogasis"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/leonardo-hernandezln"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leogasis"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/leonardo-hernandezln/"
